= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.5: Basics, Blades in the Dark, Napoleonic 20.
:toc: left
:homepage: https://blinks.github.io/dreams-in-darkness/

[verse, The National, The System Only Dreams in Total Darkness]
The system only dreams in total darkness
Why are you hiding from me?
We’re in a different kind of thing now
All night you’re talking to God

== The Basics
_Dreams in Darkness_ is a play-by-email game about elder beings fighting to
manifest in the world. We play to find out who (if anyone) wins that war.

=== Kriegsspiel
This is an old-fashioned "kriegsspiel" kind of game, where one player (the
umpire) receives orders from both sides and decides what happens. Information
and communication is much more difficult than in a normal game -- you won't
always be able to know what's happening, or where your opponents are, or
predict exactly when you'll end up in battle.

=== Setting
A ritual is underway to bring one side's elder into this world. The other side
must stop it before it completes in the next few days. Everyone should have a
copy of the map and the understanding that it isn't the territory. Each side
should keep track of their positions with tokens on their own maps, and the
umpire needs to track the positions of everyone.

TODO: Area map, two days' ride across at the longest.
TODO: Weather track. Affects the entire map.

== The Cultists
Players create a cultist as their primary contact with the world below.

(Cultists for now will have a _Blades in the Dark_ character sheet, complete
with stress and stats.)

Strategic movement in _Dreams_ is from area to area, depending on a cultist's
speed. By default, everyone can move two areas in each part of the day, but
"slow" reduces that to 1 and "fast" increases it to 3. 

=== The Mage
You channel powerful rituals through this cultist.

When you give an Occult order, your Mage can invoke a ritual of your choice:

- Fireball: +2 to Wreck until unleashed, likely in a battle.
- Flood: a body of water you choose rises dangerously; flooded rivers cannot be
  forded, flooded lakes fill their area.
- Stone Golem: You create a slow golem with Skirmish 2 that you can give march,
  assault, or rest orders. It lasts until destroyed.
- Flight: You can fly until sundown. Your speed increases to fast for the rest
  of the day, and you can ignore terrain during movement for that time.

=== The Knight
You lead an army of three gangs of (Tier 2) Thugs.

- Infantry (Loyal)
- Cavalry (Fast, Unreliable)
- Artillery (Slow, Elite)

Your orders (sent by raven) take time to reach them, and might be intercepted.
Your orders will never be entirely lost.

== The Orders
Each day is divided into six (uneven) parts: morning, midday, afternoon, dusk,
evening, and night.

At the beginning of each part, the umpire sends each other player a request for
orders from their cultist. Orders determine what they'll be doing for that
period. There are six types of orders, each with an important detail for the
player to fill in to complete the order.

. March: Travel across the map. _Detail: The route._
. Assault: Do violence to a target. _Detail: The point of attack._
. Stealth: Trespass unseen. _Detail: The point of infiltration._
. Deception: Lure, trick, or manipulate. _Detail: The method of deception._
. Social: Negotiate, bargain, or persuade. _Detail: The social connection._
. Occult: Engage a supernatural power. _Detail: The arcane method._

- Anyone that's fighting will be non-responsive for that part of the day.
- You can order a cultist to rest, which recovers some of their stress.
  (Ordering anything other than "rest" for the night phase costs stress.)
- In addition to an order, you can spend stress on a "flashback", describing
  preparations your cultist could have made prior to this moment.

== The Scenario
. Create an eight-clock: "the ritual is completed."
. Determine which side is the defender and which is the attacker.
. Ask the attacker, privately, which direction they're coming from.
. Ask the defender, privately, where the ritual is taking place. If their
  cultist spends an occult order there, they can push the clock forward.
. Attacker and defender both create cultists.

TODO: Nice area map, two days' ride across at the longest.
