= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.2: Dreaming.
:toc: left
:homepage: https://blinks.github.io/dreams-in-darkness/

[verse, The National, The System Only Dreams in Total Darkness]
The system only dreams in total darkness
Why are you hiding from me?
We’re in a different kind of thing now
All night you’re talking to God

== Introduction
_Dreams_ is a play-by-mail game for a facilitator (the *Conduit*) and three to six other players (the *Ancients*).  It's a secrets-filled role-playing game about what happens when plans come into conflict.

To play, you need a good way to communicate and a shuffled Tarot deck for seeding the world with chaos.  You don't need to be sitting in the same room, or even in the same side of the planet -- as long as you can communicate somehow, you can play.  You'll also need pencils and paper, and a way to share the map after you've drawn it.

=== The Social Contract
To keep everything going it's helpful to set expectations: how often will you be contacting players, how long is acceptable for their response, and what will you do when someone drops or needs time off?  Answering these questions at the start can help reduce hurt feelings and missed expectations later on.  When the deck runs out, this tale ends but you may continue with another -- or even a direct sequel.  Make sure you revisit the social contract.

[quote, A.E. Waite, The Pictorial Key to the Tarot (1910)]
The pathology of the poet says that "the undevout astronomer is mad"; the pathology of the very plain man says that genius is mad; and between these extremes, which stand for ten thousand analogous excesses, the sovereign reason takes the part of a moderator and does what it can.

== Ancients
Players are immortal elder beings whose power is restrained somehow.  Their only connection to the world is through people who seek them out.  The only way they can communicate to the world is through visions.

To create an ancient, decide what would happen if they had their way with the world.  What does it look like when an all-powerful elder thing arrives and isn't stopped?

Decide what's stopping you (pick a few):

- The stars must align.
- The proper words must be spoken.
- The sacrifice must be made.
- The seal must be broken.
- The child must be born.
- The tower must fall.
- The secret society must be eliminated.

[verse, The Lost Book of Gideon]
She laid the three stones below the altar,
words of power chanted through her.
The moment arrived, his eyes opened,
and she brought down the dagger.

== Landscape
A good map is crucial.  You need to be able to refer to a place or a direction and have everyone understand what you mean.  It doesn't need to be detailed, just provide enough structure that players can say: "the vision goes North over the Broken Teeth" and know what that means.

Your map needs:

- five cities -- three of them ruins, the last two in conflict.
- two mountain ranges and a volcano.
- three rivers and a lake.
- a desert and a forest.
- whatever your ancients need to destroy.
- something different, that you must decide yourselves.

Use the https://blinks.github.io/dreams-in-darkness/voronoi.html[voronoi] map generator if you need a starting point, but really just marking out a score of variously-sized areas and labeling them with their borders is enough.  As you come up with names put them on the map too, and let everyone know them.  The map is shared so make sure everyone has an up-to-date copy.

Oh, and one more thing: North probably needs to be up, or everyone will get confused.

[quote, Ammurapi]
My father behold, the enemy's ships came; my cities were burned, and they did evil things in my country. Does not my father know that all my troops and chariots are in the Land of Hatti, and all my ships are in the Land of Lukka? ... Thus, the country is abandoned to itself. May my father know it: the seven ships of the enemy that came here inflicted much damage upon us.

== Visions
The bloody membrane between worlds is thin between the ancients; you may contact them directly whenever you like. The mortal realm is further removed.  You will receive messages only when a mortal makes an effort to contact you, and send them only to mortals attuned to you who are asleep and dreaming.

The conduit will contact you when one of your cultists does.  They'll tell you something about the world above and ask for a task.  Always state the vision you send, and the intention.  Sometimes you'll have difficulty knowing where to start: the Conduit is bound to tell you the truth (as far as they know it), and might suggest a course of action.

You may send your cultists any visions you like. Explicit orders they will follow exactly. You may be sure of what they will do, but will not take advantage of the cultist's instincts in the moment. Vague orders they will interpret as best they can. They will always act in your best interest as they see it and will adapt to the situation they are in, but you will not be sure exactly what they will do.  Don't bother with contingency plans -- cultists can't remember that much, nor can visions make them understood.

[quote, H.P. Lovecraft, The Colour out of Space.]
It all began, old Ammi said, with the meteorite.

== The Conduit
Your job is to set the pace.  Choose a player who hasn't been contacted in a while and figure out what's going on with their followers.  Once you have an interesting situation in mind, draw from the Tarot deck and use it to color your ideas of how it turns out.  If you drew major arcana, figure out how to bring that power to the surface.  Contact the player with the situation from the cultists perspective, and await a response.  Responses come only when the cultist is dreaming -- and might take a while.  Life goes on above.

When you message a player:

- Tell them the truth about what happened.
- Speak from the mouth of the cultist.
- Push them into the way of another player.
- Encourage secrets, don't reveal them lightly.
- Use the names you've created.  Make new ones, as needed.
- Add subtle horrors to the message.
- Sometimes, ask one player to help detail what happens to another.

=== The Draw
_Dreams_ is about what happens when plans come into conflict.  Before you draw, you should have a critical moment in mind: the knife coming down, eyes searching the forgotten library, the bargaining table.  Let the card color the outcome.  If you look at the card and immediately see a way it applies to the situation, use that.  Otherwise, there's a list of quick ideas to latch onto below, taken from _The Pictorial Key to the Tarot_ (A.E. Waite, 1910).

TODO: Convert _Tarot_ text into questions (see _The Tower_).  The Conduit chooses who answers these questions -- some will have obvious answers they can give themselves, others might go to the player you're about to contact, still others could be directed at an unrelated player or the audience at large.

==== Major Arcana
When these are drawn, a powerful magic artifact is _also_ found in the world.

The Fool::
- "Folly, mania, extravagance, intoxication, delirium, frenzy." (Waite, 1910)
- An artifact has appeared that can be used to *sow confusion until the next sunrise*.
  What does it look like?  How does it work?

The Magician::
- "Skill, diplomacy, address, subtlety; sickness, pain, loss, disaster, snares
  of enemies; self-confidence, will." (Waite, 1910)
- An artifact has appeared that can be used for *transmutation*.  What does it look
  like?  How does it work?

The High Priestess::
- "Secrets, mystery, the future as yet unrevealed, silence, tenacity; mystery,
  wisdom, science." (Waite, 1910)
- An artifact has appeared that gives you a *mysterious vision of the world*.  What
  does it look like?  How does it work?

The Empress::
- "Fruitfulness, action, initiative, length of days; the unknown, clandestine;
  also difficulty, doubt, ignorance." (Waite, 1910)
- An artifact has appeared that *births something terrible*.  What does it look like?
  How does it work?

The Emperor::
- "Stability, power, protection, realization; a great person; aid, reason,
  conviction; also authority and will." (Waite, 1910)
- An artifact has appeared that *exerts control over another for a critical moment.*
  What does it look like?  How does it work?

The Hierophant::
- "Marriage, alliance, captivity, servitude; by another account, mercy and
  goodness; inspiration." (Waite, 1910)
- An artifact has appeared that allows you to *ask for specific advice and recieve it.*
  What does it look like?  How does it work?

The Lovers::
- "Attraction, love, beauty, trials overcome." (Waite, 1910)
- An artifact has appeared that gives you *a moment alone with someone you know.*  What
  does it look like?  How does it work?

The Chariot::
- "Succour, providence; also war, triumph, presumption, vengeance, trouble." (Waite, 1910)
- An artifact has appeared that enables you to *travel quickly until the next sunset.*
  What does it look like?  How does it work?

Strength::
- "Power, energy, action, courage, magnanimity; also complete success and
  honours." (Waite, 1910)
- An artifact has appeared that gives you *supernatural power until the next sunset.*
  What does it look like?  How does it work?

The Hermit::
- "Prudence, circumspection; also and especially treason, dissimulation,
  roguery, corruption." (Waite, 1910)
- An artifact has appeared that gives you *vision of a distant location.*  What does it
  look like?  How does it work?

Wheel of Fortune::
- "Destiny, fortune, success, elevation, luck, felicity." (Waite, 1910)
- An artifact has appeared that you can *ask for a boon and Fate will respond.*  What
  does it look like?  How does it work?

Justice::
- "Equity, rightness, probity, executive; triumph of the deserving side in
  law." (Waite, 1910)
- An artifact has appeared that *weighs yourself and another on the scales of justice.*
  What does it look like?  How does it work?

The Hanged Man::
- "Wisdom, circumspection, discernment, trials, sacrifice, intuition,
  divination, prophecy." (Waite, 1910)
- An artifact has appeared that helps you to *see clearly until the new moon.*  What
  does it look like?  How does it work?

Death::
- "End, mortality, destruction, corruption." (Waite, 1910)
- An artifact has appeared that gives you the power to *bring something to an end.*
  What does it look like?  How does it work?

Temperance::
- "Economy, moderation, frugality, management, accommodation." (Waite, 1910)
- An artifact has appeared that you can *give something you have in excess to gain
  something you lack.*  What does it look like?  How does it work?

The Devil::
- Something that was predicted has come to pass, perhaps a prophecy.  What was
  it, and who predicted it?
- An artifact has appeared with which you can *call for aid from powers you do
  not understand or control.*  What does it look like?  How does it work?

The Tower::
- What is the worst way this situation could go wrong, and what else could be
  ruined in the process?
- An artifact has appeared with which you can *utterly destroy something.*  What does
  it look like?  How does it work?

The Star::
- "Loss, theft, privation, abandonment; another reading says -- hope and bright
  prospects." (Waite, 1910)
- An artifact has appeared that gives you the power to *restore something mortal at a
  cost.*  What does it look like?  How does it work?

The Moon::
- "Hidden enemies, danger, calumny, darkness, terror, deception, occult forces,
  error." (Waite, 1910)
- An artifact has appeared that lets you *walk unseen until the next sunrise, or until
  you draw blood.*  What does it look like?  How does it work?

The Sun::
- The cultist is content with this outcome.  Why?
- An artifact has appeared that *gives you the loyalty of all who see you, until the
  next sunset.*  What does it look like?  How does it work?

Judgement::
- "Change of position, renewal, outcome. Another account specifies total loss
  though lawsuit." (Waite, 1910)
- An artifact has appeared that *raises the dead to do your bidding.*  What does it
  look like?  How does it work?

The World::
- "Assured success, recompense, voyage, route, emigration, flight, change of
  place." (Waite, 1910)
- An artifact has appeared that *transports you leagues in an instant.*  What does it
  look like?  How does it work?
