= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.2: Dreaming.
:toc: left
:homepage: https://blinks.github.io/dreams-in-darkness/

[verse, The National, The System Only Dreams in Total Darkness]
The system only dreams in total darkness
Why are you hiding from me?
We’re in a different kind of thing now
All night you’re talking to God

== Introduction
_Dreams_ is a play-by-mail game for a facilitator (the *Conduit*) and three to six other players (the *Ancients*).  It's a secrets-filled role-playing game about what happens when plans come into conflict.

To play, you need a good way to communicate and a shuffled Tarot deck for seeding the world with chaos.  You don't need to be sitting in the same room, or even in the same side of the planet -- as long as you can communicate somehow, you can play.  You'll also need pencils and paper, and a way to share the map after you've drawn it.

=== The Social Contract
To keep everything going it's helpful to set expectations: how often will you be contacting players, how long is acceptable for their response, and what will you do when someone drops or needs time off?  Answering these questions at the start can help reduce hurt feelings and missed expectations later on.  When the deck runs out, this tale ends but you may continue with another -- or even a direct sequel.  Make sure you revisit the social contract.

[quote, A.E. Waite, The Pictorial Key to the Tarot (1910)]
The pathology of the poet says that "the undevout astronomer is mad"; the pathology of the very plain man says that genius is mad; and between these extremes, which stand for ten thousand analogous excesses, the sovereign reason takes the part of a moderator and does what it can.

== Ancients
Players are immortal elder beings whose power is restrained somehow.  Their only connection to the world is through people who seek them out.  The only way they can communicate to the world is through visions.

To create an ancient, decide what would happen if they had their way with the world.  What does it look like when an all-powerful elder thing arrives and isn't stopped?

Choose three prophecies.  When they all come true, nothing is stopping you.

The wine jug must be emptied::
You are attuned to *The Fool*, which can be used to *sow confusion until the
next sunrise*.

The proper words must be spoken::
You are attuned to *The Magician*, which can be used to *transmute elements.*
Your cultists are quick (+Mercury).

The seal must be broken::
You are attuned to *The High Priestess*, which can give you a *mysterious
vision of the world*

The child must be born::
You are attuned to *The Empress*, which *births something terrible.*  Your
cultists are persuasive (+Venus).

The leader must be overthrown::
You are attuned to *The Emperor*, which *exerts control over another for a
critical moment.*  Your cultists are lucky (+Jupiter).

The criminal must be given mercy::
You are attuned to *The Hierophant*, which allows you to *ask for specific
advice and recieve it.*

The secret society must be eliminated::
You are attuned to *The Lovers*, which gives you *a moment alone with someone
you know.*  Your cultists are persuasive (+Venus).

The war must begin::
You are attuned to *The Chariot*, which enables you to *travel quickly until
the next sunset.*

The game must be won::
You are attuned to *Strength*, which gives you *supernatural power until the
next sunset.*  Your cultists are courageous and steady (+Mars).

The child must be abandoned::
You are attuned to *The Hermit*, which gives you *vision of a distant
location.*

The coin must be tossed::
You are attuned to *Wheel of Fortune*, which you can *ask for a boon: Fate will respond.*

Justice must be done::
You are attuned to *Justice*, which *weighs yourself and another on the scales
of justice.*

The trials must be overcome::
You are attuned to *The Hanged Man*, which helps you to *see clearly until the
new moon.*

The hero must die::
You are attuned to *Death*, which gives you the power to *bring something to an
end.*  Sometimes, the end is only temporary.

The path must be followed::
You are attuned to *Temperance*, which *takes something you have in excess to
give you something you lack.*

The sacrifice must be made::
You are attuned to *The Devil*, with which you can *call for aid from powers
you do not understand or control.*

The tower must fall::
You are attuned to *The Tower* which can be used to *utterly destroy
something.*  Your cultists are courageous and steady (+Mars).

The stars must align::
You are attuned to *The Star* which can *restore something mortal at a cost.*

The terror must come::
You are attuned to *The Moon*, which lets you *walk unseen until the next
sunrise, or until you draw blood.*  Your cultists are secretive (+Moon).

The empire must rise::
You are attuned to *The Sun*, which *gives you the loyalty of all who see you,
until the next sunset.*  Your cultists are powerful (+Sun).

The dead must be judged::
You are attuned to *Judgement*, which *raises the dead to do your bidding.*

The lost must be found::
You are attuned to *The World*, which *transports you leagues in an instant.*

[verse, The Lost Book of Gideon]
She laid the three stones below the altar,
words of power chanted through her.
The moment arrived, his eyes opened,
and she brought down the dagger.

== Landscape
A good map is crucial.  You need to be able to refer to a place or a direction and have everyone understand what you mean.  It doesn't need to be detailed, just provide enough structure that players can say: "the vision goes North over the Broken Teeth" and know what that means.

Your map needs:

- five cities -- three of them ruins, the last two in conflict.
- two mountain ranges and a volcano.
- three rivers and a lake.
- a desert and a forest.
- whatever your ancients need to destroy.
- something different, that you must decide yourselves.

Use the https://blinks.github.io/dreams-in-darkness/voronoi.html[voronoi] map generator if you need a starting point, but really just marking out a score of variously-sized areas and labeling them with their borders is enough.  As you come up with names put them on the map too, and let everyone know them.  The map is shared so make sure everyone has an up-to-date copy.

Oh, and one more thing: North probably needs to be up, or everyone will get confused.

[quote, Ammurapi]
My father behold, the enemy's ships came; my cities were burned, and they did evil things in my country. Does not my father know that all my troops and chariots are in the Land of Hatti, and all my ships are in the Land of Lukka? ... Thus, the country is abandoned to itself. May my father know it: the seven ships of the enemy that came here inflicted much damage upon us.

== Visions
The bloody membrane between worlds is thin between the ancients; you may contact them directly whenever you like. The mortal realm is further removed.  You will receive messages only when a mortal makes an effort to contact you, and send them only to mortals attuned to you who are asleep and dreaming.

Once the map is built and the prophecies are written, the game proper can begin.

The conduit will contact you -- awakening your ancient -- when a cultist figures out the proper ritual.  They have no idea what they've uncovered, but your infinite power is overwhelming to any mortal will.  In their trance, they'll tell you something about the world above and ask for a task.  Always state the vision you send, and the intention.  Sometimes you'll have difficulty knowing where to start: the Conduit is bound to tell you the truth (as far as they know it), and might suggest a course of action.

As they sleep, you may send your cultists any visions you like. Explicit orders they will follow exactly, to the best of their ability. You may be sure of what they will do, but will not take advantage of the cultist's instincts in the moment. Vague orders they will attempt to interpret, but not in the evil genie sort of way. They will always act in your best interest as they see it and will adapt to the situation they are in, but you will not be sure exactly what they will do.  Don't bother with contingency plans -- cultists can't remember that much, nor can visions make them understood.

[quote, H.P. Lovecraft, The Colour out of Space.]
It all began, old Ammi said, with the meteorite.

== The Conduit
You set the pace and describe the world.  You do this by finding _conflicts,_ figuring out the possible results, drawing to inject some chaos, and reporting back to the players.

Before you draw, you should have a critical moment in mind: the knife coming down, eyes searching the forgotten library, the bargaining table.  Let the card color the outcome.

Anytime the outcome is uncertain is a possible critical moment.  This could be a cultist attempting something interesting and risky, or two cultists wanting different things in the same place.  Divide participants into at most three groups: the attackers, the defenders, and the bystanders.  The first two groups are in opposition, and you'll be drawing for the attackers.

Determine the sphere of conflict:

The Sun:: A conflict of raw power or strength.
Mercury:: A conflict of speed or skill.
Venus:: A conflict of persuasion.
The Moon:: A conflict of wisdom, secrets, or magic.
Mars:: A conflict of courage or constitution.
Saturn:: A conflict of patience or solitude.
Jupiter:: A conflict of pure luck.

Weigh both sides on the scales.  Count positive when things are in the attacker's favor and negative if they're in the defender's favor:

- Does a side have more people actively working for it?  Count one for that side.
- Does a side have the element of surprise?  Count one for it.
- Does the location help or hurt a side?  Count one for that, too.
- Does one side's intentions more closely match an ancient's will?  Count one for it.

Then draw:

- If you draw major arcana, a relic is found.  Contact the player attuned to it and ask what it looks like and how to unlock its power.  Draw again for the situation.
- If you draw a court card (page, knight, queen, or king), an important character appears.  Perhaps a new cultist, perhaps just someone important to the setting.  Figure out who they are.  Draw again for the situation.
- If you draw an ace, the plan succeeds wildly, and the attackers gain power; give them new aspects reflecting their growth.
- If you draw any other card, reflect on the image and what it might mean, and then check the table to determine where it falls on the spheres.  The closer to the sphere of conflict it lies, the better for the attackers: exact match is +2, and each step away (wrap from top to bottom; TODO: image) reduces it.  At the exact opposite, it counts as -1.

.Numbered Cards
|===
|#  |Wands    |Cups     |Swords   |Coins
|2  |Mars     |Venus    |Moon     |Jupiter
|3  |Sun      |Mercury  |Saturn   |Mars
|4  |Venus    |Moon     |Jupiter  |Sun
|5  |Saturn   |Mars     |Venus    |Mercury
|6  |Jupiter  |Sun      |Mercury  |Moon
|7  |Mars     |Venus    |Moon     |Saturn
|8  |Mercury  |Saturn   |Jupiter  |Sun
|9  |Moon     |Jupiter  |Mars     |Venus
|10 |Saturn   |Mars     |Sun      |Mercury
|===

Contact the player with the situation from the cultists perspective, and await a response.  Responses come only when the cultist is dreaming -- and might take a while.  Life goes on above.

When you message a player:

- Tell them the truth about what happened.
- Speak from the mouth of the cultist.
- Push them into the way of another player.
- Encourage secrets, don't reveal them lightly.
- Use the names you've created.  Make new ones, as needed.
- Add subtle horrors to the message.
- Sometimes, ask one player to help detail what happens to another.

