= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.2: Dreaming.
:toc: left
:homepage: https://blinks.github.io/battle-mage/

[verse, The National, The System Only Dreams in Total Darkness]
The system only dreams in total darkness
Why are you hiding from me?
We’re in a different kind of thing now
All night you’re talking to God

== Introduction
_Dreams_ is a play-by-mail game for a facilitator (the *conduit*) and up to six other players (the *ancients*).  It's a secrets-filled role-playing game with strict ideas about time and space.

To play, everyone needs a copy of the map, and the conduit also needs a shuffled Tarot deck for seeding the world with chaos.  You don't need to be sitting in the same room, or even in the same side of the planet -- as long as you can communicate somehow, you can play.

[quote, A.E. Waite, The Pictorial Key to the Tarot (1910)]
The pathology of the poet says that "the undevout astronomer is mad"; the pathology of the very plain man says that genius is mad; and between these extremes, which stand for ten thousand analogous excesses, the sovereign reason takes the part of a moderator and does what it can. 

=== The Social Contract
To keep everything going, it's helpful to set expectations: how often will you be contacting players?  How long is acceptable for their response?  What will you do when someone drops or needs time off?  Answering these questions at the start can help reduce hurt feelings and missed expectations later on.  When the deck runs out, this tale ends but you may continue with another -- or even a direct sequel.  Revisit the social contract.

== Ancients

=== Nix, Voidbound
[quote, H.P. Lovecraft, The Colour out of Space.]
It all began, old Ammi said, with the meteorite.

Cultists:: Yrrratha, Korthath, X'parthak.  (Nihilists.)

Barriers:: The vast distance of space, traversable only by the Black Gates once closed to (another).  The unrecognizable physics of this world, shaped once by (another) with a powerful eldritch word spoken in the Circle of the Star.  The signal to come, which only a relic of (another) could transmit from the Obsidian Spire.

=== Arcturus, Forgotten Mage
[verse, The Lost Book of Gideon, Chapter 8 verse 5]
She laid the three stones below the altar,
words of power chanted through her.
The moment arrived, his eyes opened,
and she brought down the dagger.

Cultists:: Antharia, Parthos the Mad, Gray Yiyinona. (Curious power-seeking wizards.)

Barriers:: The three crystals embedded in Roderick's gravestone that power your prison, and resonate with energy wanted by (another).  The labyrinthian caverns above your tomb, which hold artifacts of (another).  Your name, lost in the pages of (another)'s forbidden tome.

=== Agon, Dead God of War
[quote, Ammurapi]
My father behold, the enemy's ships came; my cities were burned, and they did evil things in my country.

Cultists:: Sister Agatha the White, Brother Marcos the Red, Mother. (Looking for glory.)

Barriers:: The Ladies Templar, who hid your five relics across the lands; they were sought by followers of (another) for dark things.  The Lost Book of Gideon, which followers of (another) recorded your most powerful rituals in.  Your divine hammer, which destroyed (another) ages ago and holds runes that drive those who read them mad.

=== Lady of Shadow
Weak from an ancient defeat, almost forgotten in the world above.

Cultists:: Nameless.  (Assassins, hoards of them.)

=== Hivemind of Drakon
> Now that idea has burrowed itself so deep into my head that reading orders is difficult to understand in any other way...

Cultists:: Powerful world figures.  (Now puppets to your subconscious.)

=== The Three Fates
Someday, you'll sing the song that ends the world.  All in its proper time.

Cultists:: Lena the Chantress, Bard, Marantha of Tal.  (Singers and storytellers.)

== Visions of Play
Pick playbooks and one of their barriers -- never the same barrier as another player, though you may share books.  Write another ancient's name in the blank and share it with them.  Where places are mentioned, add them to the map and show the others where they are.  You have no cultists yet.

Also add these locations to the map:

- The Last City.
- Dagger Fields.
- The Desert.
- Two mountain ranges, name them. (Broken Teeth, The Axe, Grey Ridge)
- Two ruins, name them. (Ikshatha, Croth)
- Three rivers, name them. (Tears of Asha, River Zzik, Darkwater Creek)

If any area on the map doesn't yet have a name, name it.

The bloody membrane between worlds is thin between the ancients, you may contact them directly whenever you like. The mortal realm is further removed.  You will receive messages only when a mortal makes an effort to contact you, and send them only to mortals attuned to you who are asleep and dreaming.

The conduit will contact you when a cultist does.  They'll tell you something about the world above and ask for a task.  Always state the vision you send, and the intention.  Sometimes you'll have difficulty knowing where to start: the Conduit is bound to tell you the truth (as far as they know it), and might suggest a course of action.

You may send your cultists any visions you like. Explicit orders they will follow exactly. You may be sure of what they will do, but will not take advantage of the cultist's instincts in the moment. Vague orders they will interpret as best they can. They will always act in your best interest as they see it and will adapt to the situation they are in, but you will not be sure exactly what they will do.  Don't bother with contingency plans -- cultists can't remember that much.

== The Conduit

Your job is to set the pace.  Choose a player who hasn't been contacted in a while and figure out what's going on with their followers.  Once you have an interesting situation in mind, draw from the Tarot deck and use it to color your ideas of how it turns out.  If you drew major arcana, figure out how to bring that power to the surface.  Contact the player with the situation from the cultists perspective, and await a response.  Responses come only when the cultist is dreaming -- and might take a while.  Life goes on above.

=== Principles

- *Speak through the cultists.*
- *Bind them together, don't make them friends.*
- *Encourage secrets, don't reveal them lightly.*
- *Add place names, use them.*
- *Suggest the next task.*
- *Let the horror hang in the air.*
- *Sometimes, ask another player.*

== The Cards
Drawn cards provide for chaotic changes in a sometimes static world.  Every card you draw should color your understanding of the situation.  Did you think that battle was a simple matter of force?  Draw *The Tower* and see it all come crashing down.  Some cards have other important effects:

*Major arcana* surface new artifacts of great power.  While the powers are specific, the shape the artifact takes should be suggested by the player -- ask them.

*Court cards* (Page, Knight, Queen, King) are new cultists.  Someone is always searching for the ancients, and sometimes they succeed.

=== Major Arcana
Relics in the world that can invoke powerful rituals.

The Fool:: Sow confusion until the next sunrise.
The Magician:: Transmute an object.
The High Priestess:: Receive a vision of the world.
The Empress:: Birth something terrible.
The Emperor:: Exert control over another for a critical moment.
The Hierophant:: Ask for specific advice and recieve it.
The Lovers:: You have a moment alone with someone you know.
The Chariot:: Travel quickly until the next sunset.
Strength:: Gain supernatural power until the next sunset.
The Hermit:: Scry on a distant location.
Wheel of Fortune:: Ask fate for a boon.
Justice:: Weigh yourself and another on the scales.
The Hanged Man:: See clearly until the new moon.
Death:: Force a transition.
Temperance:: Give up something you have in excess to gain something you lack.
The Devil:: Call on monstrous powers beyond your ken for aid.
The Tower:: Destroy something.
The Star:: Restore something mortal.
The Moon:: You walk unseen until the next sunrise, or until you draw blood.
The Sun:: Gain the loyalty of all who see you, until the next sunset.
Judgement:: Raise the dead to do your bidding.
The World:: Step leagues in an instant.
