= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.2: Dreaming.
:toc: left
:homepage: https://blinks.github.io/battle-mage/

== Introduction
_Dreams_ is a play-by-mail game for a facilitator (the *conduit*) and up to
six other players (the *ancients*).  It's a secrets-filled role-playing game
with strict ideas about time and space.

To play, everyone needs a copy of the map, and the conduit also needs a
shuffled Tarot deck for seeding the world with chaos.  You don't need to be
sitting in the same room, or even in the same side of the planet -- as long as
you can communicate somehow, you can play.

The bloody membrane between worlds is thin between the ancients, you may
contact them directly whenever you like. The mortal realm is further removed.
You will receive messages only when a mortal makes an effort to contact you,
and send them only to mortals attuned to you who are asleep and dreaming.

== Ancients

=== The Alchemist
Your Philosopher’s Stone didn’t work the way you thought it would, and now
you’re stuck ... somewhere.

Cultists contact you by melting gold and dipping in a finger.  Choose their names:

- Child of Gold
- Daughter of Silver
- Son of Iron

Barriers to your return:

- Your tomb was lost under Starfall Marsh and must be found again.
- Your work was burnt, but pages still survive in the ruins of the Eternal
  City; they must be gathered.
- Your name is lost to the ages, but is whispered by hot steel in flesh.  It
  must be spoken in daylight at the tallest peak of the Broken Teeth.

=== Yed-id of the Infinite Void Or Whatever
Like, you know?

Cultists contact you by rolling their eyes so far back they disappear.

- Apathasia
- Vorgon the Peeved
- Hofun

Barriers to your return:

- The meadows at Archangel's Rest are still remembered fondly.  It must be
  cleansed.
- The empire's royal bloodline is unbroken.  It must be cut down at the Red
  City.
- Acolytes still learn of your failure at the Monastery of the Rook.  It must
  be destroyed.

== Visions of Play
Pick playbooks and answer their questions.  Where places are mentioned, add
them to the map and show the others where they are.  The conduit will draw each
ancient three cards from the Tarot and tell you what they mean.

The conduit will contact you when a cultist does.  They'll tell you something
about the world above and ask for a task.  Always state the vision you send,
and the intention.

You may send your cultists any visions you like. Explicit orders they will
follow exactly. You may be sure of what they will do, but will not take
advantage of the cultist's instincts in the moment. Vague orders they will
interpret as best they can. They will always act in your best interest as they
see it and will adapt to the situation they are in, but you will not be sure
exactly what they will do.

== The Conduit
TODO
