= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.2: Dreaming.
:toc: left
:homepage: https://blinks.github.io/battle-mage/

== Introduction
_Dreams_ is a play-by-mail game for a facilitator (the *conduit*) and up to
six other players (the *ancients*).  It's a secrets-filled role-playing game
with strict ideas about time and space.

To play, everyone needs a copy of the map, and the conduit also needs a
shuffled Tarot deck for seeding the world with chaos.  You don't need to be
sitting in the same room, or even in the same side of the planet -- as long as
you can communicate somehow, you can play.

The bloody membrane between worlds is thin between the ancients, you may
contact them directly whenever you like. The mortal realm is further removed.
You will receive messages only when a mortal makes an effort to contact you,
and send them only to mortals attuned to you who are asleep and dreaming.

== Ancients

=== The Alchemist
Your Philosopher’s Stone didn’t work the way you thought it would, and now
you’re stuck ... somewhere.

Cultists contact you by melting gold and dipping in a finger.  Choose their names:

- Child of Gold
- Daughter of Silver
- Son of Iron

Barriers to your return:

- Your tomb was lost under Starfall Marsh and must be found again, but the air
  is poisonous all throughout those lands.
- Your work was burnt, but pages still survive in the ruins of the Eternal
  City. They must be gathered, but ghouls wander the streets.
- Your name is lost to the ages, but is whispered by hot steel in flesh.  It
  must be spoken in daylight at the tallest peak of the Broken Teeth.

=== Yed-id of the Infinite Void Or Whatever
Like, you know?

Cultists contact you by rolling their eyes so far back they disappear.

- Apathasia
- Vorgon the Peeved
- Hofun

Barriers to your return:

- The meadows at Archangel's Rest are remembered fondly.  They must be
  cleansed, but She still watches over it.
- The empire's royal bloodline is unbroken.  It must be cut down at the Red
  City, but the old legions still stand.
- Acolytes still learn of your failure at the Monastery of the Rook.  It must
  be destroyed, but the path is difficult.

== Visions of Play
Pick playbooks and answer their questions.  Where places are mentioned, add
them to the map and show the others where they are.  The conduit will draw each
ancient three cards from the Tarot and tell you what they mean.

The conduit will contact you when a cultist does.  They'll tell you something
about the world above and ask for a task.  Always state the vision you send,
and the intention.

You may send your cultists any visions you like. Explicit orders they will
follow exactly. You may be sure of what they will do, but will not take
advantage of the cultist's instincts in the moment. Vague orders they will
interpret as best they can. They will always act in your best interest as they
see it and will adapt to the situation they are in, but you will not be sure
exactly what they will do.

== The Conduit
TODO

== The Cards
Drawn cards provide for chaotic changes in a sometimes static world.

=== Major Arcana
Relics in the world that can invoke powerful rituals.

The Fool:: Sow confusion until the next sunrise.
The Magician:: Transmute an object.
The High Priestess:: Receive a vision of the world.
The Empress:: Birth something terrible.
The Emperor:: Exert control over another for a critical moment.
The Hierophant:: Ask for specific advice and recieve it.
The Lovers:: Connect to another until the next sunrise.
The Chariot:: Travel quickly until the next sunset.
Strength:: Gain supernatural power until the next sunset.
The Hermit:: Scry on a distant location.
Wheel of Fortune:: Ask fate for a boon.
Justice:: Weigh yourself and another on the scales.
The Hanged Man:: See clearly until the new moon.
Death:: Force a transition.
Temperance:: Give up something you have in excess to gain something you lack.
The Devil:: Call on monstrous powers beyond your ken for aid.
The Tower:: Destroy something.
The Star:: Restore something mortal.
The Moon:: You walk unseen until the next sunrise, or until you draw blood.
The Sun:: Gain the loyalty of all who see you, until the next sunset.
Judgement:: Raise the dead to do your bidding.
The World:: Step leagues in an instant.

=== Wands

Ace:: TODO
2:: TODO
3:: TODO
4:: TODO
5:: TODO
6:: TODO
7:: TODO
8:: TODO
9:: TODO
10:: TODO
Page:: TODO
Knight:: TODO
Queen:: TODO
King:: TODO

=== Cups

Ace:: TODO
2:: TODO
3:: TODO
4:: TODO
5:: TODO
6:: TODO
7:: TODO
8:: TODO
9:: TODO
10:: TODO
Page:: TODO
Knight:: TODO
Queen:: TODO
King:: TODO

=== Swords

Ace:: TODO
2:: TODO
3:: TODO
4:: TODO
5:: TODO
6:: TODO
7:: TODO
8:: TODO
9:: TODO
10:: TODO
Page:: TODO
Knight:: TODO
Queen:: TODO
King:: TODO

=== Pentacles

Ace:: TODO
2:: TODO
3:: TODO
4:: TODO
5:: TODO
6:: TODO
7:: TODO
8:: TODO
9:: TODO
10:: TODO
Page:: TODO
Knight:: TODO
Queen:: TODO
King:: TODO
