= Dreams in Darkness
Adam Blinkinsop <github.com/blinks>
v0.3: Prophecy.
:toc: left
:homepage: https://blinks.github.io/dreams-in-darkness/

[verse, The National, The System Only Dreams in Total Darkness]
The system only dreams in total darkness
Why are you hiding from me?
We’re in a different kind of thing now
All night you’re talking to God

== Introduction
_Dreams_ is a play-by-mail game for a facilitator (the *Conduit*) and three to six other players (the *Ancients*).  It's a secrets-filled role-playing game about what happens when plans come into conflict.

To play, you need a good way to communicate and a shuffled Tarot deck for seeding the world with chaos.  You don't need to be sitting in the same room, or even in the same side of the planet -- as long as you can communicate somehow, you can play.  You'll also need pencils and paper, and a way to share the map after you've drawn it.

=== The Social Contract
To keep everything going it's helpful to set expectations: how often will you be contacting players, how long is acceptable for their response, and what will you do when someone drops or needs time off?  Answering these questions at the start can help reduce hurt feelings and missed expectations later on.  When the deck runs out, this tale ends but you may continue with another -- or even a direct sequel.  Make sure you revisit the social contract.

[quote, A.E. Waite, The Pictorial Key to the Tarot (1910)]
The pathology of the poet says that "the undevout astronomer is mad"; the pathology of the very plain man says that genius is mad; and between these extremes, which stand for ten thousand analogous excesses, the sovereign reason takes the part of a moderator and does what it can.

== Ancients
Players are immortal elder beings whose power is restrained somehow.  Their only connection to the world is through people who seek them out.  The only way they can communicate to the world is through visions.

To create an ancient, decide what would happen if they had their way with the world.  What does it look like when an all-powerful elder thing arrives and isn't stopped?

Choose three prophecies.  When they all come true, nothing is stopping you.  Each is attuned to a powerful artifact, lost for ages.  If they emerge in play, you can decide what they look like and how their power might be accessed, but not who ends up holding them...

The wine jug must be emptied::
You are attuned to *The Fool*, which can be used to *sow confusion until the
next sunrise*.  Your cultists are naïve.

The proper words must be spoken::
You are attuned to *The Magician*, which can be used to *transmute elements.*
Your cultists are quick.

The seal must be broken::
You are attuned to *The High Priestess*, which can give you a *mysterious
vision of the world.*  Your cultists are subtle.

The child must be born::
You are attuned to *The Empress*, which *births something terrible.*  Your
cultists are persuasive.

The leader must be overthrown::
You are attuned to *The Emperor*, which *exerts control over another for a
critical moment.*  Your cultists are political.

The criminal must be given mercy::
You are attuned to *The Hierophant*, which allows you to *ask for specific
advice and recieve it.*  Your cultists are organized.

The secret society must be eliminated::
You are attuned to *The Lovers*, which gives you *a moment alone with someone
you know.*  Your cultists come in pairs.

The war must begin::
You are attuned to *The Chariot*, which enables you to *travel quickly until
the next sunset.*  Your cultists are soldiers.

The game must be won::
You are attuned to *Strength*, which gives you *supernatural power until the
next sunset.*  Your cultists are courageous.

The child must be abandoned::
You are attuned to *The Hermit*, which gives you *vision of a distant
location.*  Your cultists are wanderers.

The coin must be tossed::
You are attuned to *Wheel of Fortune*, which you can *ask for a boon: Fate will
respond.*  Your cultists are lucky.

Justice must be done::
You are attuned to *Justice*, which *weighs yourself and another on the scales
of justice.*  Your cultists are just.

The trials must be overcome::
You are attuned to *The Hanged Man*, which helps you to *see clearly until the
new moon.*  Your cultists are enlightened.

The hero must die::
You are attuned to *Death*, which gives you the power to *bring something to an
end.*  Your cultists are nihilists.

The path must be followed::
You are attuned to *Temperance*, which *takes something you have in excess to
give you something you lack.*  Your cultists have self-control.

The sacrifice must be made::
You are attuned to *The Devil*, with which you can *call for aid from powers
you do not understand or control.*  Your cultists cannot escape you.

The tower must fall::
You are attuned to *The Tower* which can be used to *utterly destroy
something.*  Your cultists can see through illusions.

The stars must align::
You are attuned to *The Star* which can *restore something mortal at a cost.*
Your cultists are peaceful.

The terror must come::
You are attuned to *The Moon*, which lets you *walk unseen until the next
sunrise, or until you draw blood.*  Your cultists are secretive.

The empire must rise::
You are attuned to *The Sun*, which *gives you the loyalty of all who see you,
until the next sunset.*  Your cultists are powerful.

The dead must be judged::
You are attuned to *Judgement*, which *raises the dead to do your bidding.*
Your cultists are faithful.

The lost must be found::
You are attuned to *The World*, which *transports you leagues in an instant.*
Your cultists are scholars.

[verse, The Lost Book of Gideon]
She laid the three stones below the altar,
words of power chanted through her.
The moment arrived, his eyes opened,
and she brought down the dagger.

== Landscape
A good map is crucial.  You need to be able to refer to a place or a direction and have everyone understand what you mean.  It doesn't need to be detailed, just provide enough structure that players can say: "the vision goes North over the Broken Teeth" and know what that means.

Your map needs:

- five cities -- three of them ruins, the last two in conflict.
- two mountain ranges and a volcano.
- three rivers and a lake.
- a desert and a forest.
- whatever your ancients need to destroy.
- something different, that you must decide yourselves.

Use the https://blinks.github.io/dreams-in-darkness/voronoi.html[voronoi] map generator if you need a starting point, but really just marking out a score of variously-sized areas and labeling them with their borders is enough.  As you come up with names put them on the map too, and let everyone know them.  The map is shared so make sure everyone has an up-to-date copy.

Oh, and one more thing: North probably needs to be up, or everyone will get confused.

[quote, Ammurapi]
My father behold, the enemy's ships came; my cities were burned, and they did evil things in my country. Does not my father know that all my troops and chariots are in the Land of Hatti, and all my ships are in the Land of Lukka? ... Thus, the country is abandoned to itself. May my father know it: the seven ships of the enemy that came here inflicted much damage upon us.

== Visions
The bloody membrane between worlds is thin between the ancients; you may contact them directly whenever you like. The mortal realm is further removed.  You will receive messages only when a mortal makes an effort to contact you, and send them only to mortals attuned to you who are asleep and dreaming.

Once the map is built and the prophecies are written, the game proper can begin.

The conduit will contact you -- awakening your ancient -- when a cultist figures out the proper ritual.  They have no idea what they've uncovered, but your infinite power is overwhelming to any mortal will.  In their trance, they'll tell you something about the world above and ask for a task.  Always state the vision you send, and the intention.  Sometimes you'll have difficulty knowing where to start: the Conduit is bound to tell you the truth (as far as they know it), and might suggest a course of action.

As they sleep, you may send your cultists any visions you like. Explicit orders they will follow exactly, to the best of their ability. You may be sure of what they will do, but will not take advantage of the cultist's instincts in the moment. Vague orders they will attempt to interpret, but not in the evil genie sort of way. They will always act in your best interest as they see it and will adapt to the situation they are in, but you will not be sure exactly what they will do.  Don't bother with contingency plans -- cultists can't remember that much, nor can visions make them understood.

[quote, H.P. Lovecraft, The Colour out of Space.]
It all began, old Ammi said, with the meteorite.

== The Conduit
You set the pace and describe the world.  You do this by finding _conflicts,_ figuring out the possible results, drawing to inject some chaos, and reporting back to the players.

Before you draw, you should have a critical moment in mind: the knife coming down, eyes searching the forgotten library, the bargaining table.  Use the map -- keep a pawn or a die for each cultist on it, and move them around as the visions take them.  When two cultists meet tends to be a critical moment -- use their traits to determine what that meeting looks like.  When a plan comes to a head is another -- figure out what could go wrong and draw for it.

Anytime the outcome is uncertain is a possible critical moment.  This could be a cultist attempting something interesting and risky, or two cultists wanting different things in the same place.  Divide participants into at most three groups: the attackers, the defenders, and the bystanders.  The first two groups are in opposition, and you'll be drawing for the attackers.  If you don't have anybody for the defender group, create somebody: perhaps a monstrous force, perhaps still human, perhaps traps or just difficult terrain.

Determine the sphere of conflict:

The Sun:: A conflict of raw power or strength.
Mercury:: A conflict of speed or skill.
Venus:: A conflict of persuasion.
The Moon:: A conflict of wisdom, secrets, or magic.
Mars:: A conflict of courage or constitution.
Saturn:: A conflict of patience or solitude.
Jupiter:: A conflict of pure luck.

Weigh everything on the scales (think character traits, equipment and magical effects, the landscape, and so on) and come up with an obvious, interesting outcome.  Then draw:

- If you draw major arcana, a relic is unearthed during the conflict.  Contact the player attuned to it and ask what it looks like and how to unlock its power.
- If you draw a court card (page, knight, queen, or king), an important character appears.  Perhaps a new cultist, perhaps just someone important to the setting.  They're on the attacking side if oriented heads-up, defending side otherwise.
- If you draw an ace, the plan succeeds wildly, and the attackers gain power; give them a new aspect reflecting their growth in the sphere of conflict.

No matter what you draw, reflect on the image and what it might mean, updating your outcome with that understanding.  Record both the card and the outcome you chose in a campaign log.  Contact the player with the situation from the cultists perspective, and pick another conflict to resolve.  Responses come only when the cultist is dreaming -- and might take a while.  Life goes on above.

When you message a player:

- Tell them the truth about what happened.
- Speak from the mouth of the cultist.
- Push them into the way of another player.
- Encourage secrets, don't reveal them lightly.
- Use the names you've created.  Make new ones, as needed.
- Add subtle horrors to the message.
- Sometimes, ask one player to help detail what happens to another.

